title: Trinh Le-Khanh
url: 'https://trinhlk.github.io'
baseurl: ''

# Profile information
yourname: Trinh Le-Khanh
title: 'Researcher'
location: Lille, France

## Social Profiles
facebook: https://www.facebook.com/trinh.lekhanh1
twitter: https://twitter.com/TrinhLeKhanh
linkedin: https://www.linkedin.com/in/l%C3%AA-kh%C3%A1nh-tr%C3%ACnh-874994152/
github: https://github.com/TrinhLK