title: Trinh Le-Khanh
url: 'https://trinhlk.github.io'
baseurl: ''

# Profile information
yourname: Le Khanh Trinh
title: 'Lecturer'
location: Hanoi, Vietnam

## Social Profiles
scholar: https://scholar.google.com/citations?user=Y1d3evoAAAAJ&hl=vi
linkedin: https://www.linkedin.com/in/l%C3%AA-kh%C3%A1nh-tr%C3%ACnh-874994152/
github: https://github.com/TrinhLK